### ISSUE TITLE
Issues with `tooltippedIcon.onDestroyed`

### ISSUE THREAD

**Issue by pouya-eghbali** [mozfet/meteor-materialize-icons#1]
Regarding [1]

I updated the package to 1.1.7 in my project and in my copy of autoform-materialize, it didn't solve the issue. I tried to clone this repository and investigate what's wrong and I noticed this repo is at 1.1.6.

Regarding [2]

It seems like changing

```JavaScript
instance.tooltip.destroy()
```

to

```JavaScript
if (instance.tooltip) {
    instance.tooltip.destroy()
}
```

in `imports/ui/components/tooltippedIcon/tooltippedIcon.js` line 119 solves the problems in [2], it cleans the dom and there are no exceptions thrown in the console.

[1] https://github.com/mozfet/meteor-autoform-materialize/issues/71#issuecomment-491369646
[2] https://github.com/mozfet/meteor-autoform-materialize/issues/71#issuecomment-491275381

In case it matters:
Meteor: 1.8.1
Autoform: 6.3.0

**Comment by mozfet** [comment]
I only checked it into GitHub this morning. That is how I solved it as well… strange...

**Comment by pouya-eghbali** [comment]
Ok perfect, I cloned before you pushed the code, I close this.
